/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recordings */
        get: operations["recordings_v1_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_v1_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fixtures/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture */
        get: operations["fixture_v1_fixtures__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs */
        post: operations["runs_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay */
        post: operations["replay_v1_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Run */
        post: operations["import_run_v1_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select */
        post: operations["select_v1_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rankings */
        post: operations["rankings_v1_rankings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compare-rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ranking Answers */
        post: operations["ranking_answers_v1_compare_rankings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "generated" | "no_context" | "error";
            /** Model */
            model?: string | null;
            /**
             * Elapsed Ms
             * @default 0
             */
            elapsed_ms: number;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Cached Input Tokens */
            cached_input_tokens?: number | null;
            /** Citations */
            citations?: string[];
            /** Unknown Citations */
            unknown_citations?: string[];
            /** Source Map */
            source_map?: {
                [key: string]: string;
            };
            /** Error Code */
            error_code?: string | null;
            /** Finish Reason */
            finish_reason?: string | null;
            /** Settings */
            settings?: {
                [key: string]: string | number;
            };
        };
        /** Comparison */
        Comparison: {
            /** Input Hash */
            input_hash: string;
            /** Policy Version */
            policy_version: string;
            baseline: components["schemas"]["Answer"];
            selected: components["schemas"]["Answer"];
            /** Baseline Ids */
            baseline_ids: string[];
            /** Selected Ids */
            selected_ids: string[];
            /**
             * Selection Source
             * @enum {string}
             */
            selection_source: "live" | "fixture";
            /** Baseline Stage Ms */
            baseline_stage_ms: number;
            /** Selected Stage Ms */
            selected_stage_ms: number;
            /** Selection Original Ms */
            selection_original_ms: number;
            /** Baseline Cost Usd */
            baseline_cost_usd: number | null;
            /** Selected Cost Usd */
            selected_cost_usd: number | null;
            /** Selection Cost Usd */
            selection_cost_usd: number | null;
            /**
             * Cost Basis
             * @default Estimate from configured per-million rates; excludes retrieval and caching discounts
             */
            cost_basis: string;
            /**
             * Timing Basis
             * @default Generation measured now; selected stage adds original scoring time. Retrieval excluded.
             */
            timing_basis: string;
            /**
             * Citation Check
             * @default Citation IDs checked; factual support and answer correctness are not graded
             */
            citation_check: string;
        };
        /** Decision */
        Decision: {
            /** Id */
            id: string;
            /** Input Index */
            input_index: number;
            /** Relevance */
            relevance: number | null;
            /** Model */
            model: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Selected */
            selected: boolean | null;
            /** Returned */
            returned: boolean;
            /** Original Rank */
            original_rank?: number | null;
            /** Jev Rank */
            jev_rank?: number | null;
            /** Fusion Score */
            fusion_score?: number | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "retained" | "below_threshold" | "beyond_top_n" | "beyond_token_budget" | "bypassed" | "pinned" | "group_retained";
        };
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Group Id */
            group_id?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportedRun */
        ImportedRun: {
            view: components["schemas"]["RunView"];
            comparison?: components["schemas"]["Comparison"] | null;
        };
        JsonValue: unknown;
        /** Judgment */
        Judgment: {
            /** Relevance */
            relevance: number;
            /** Model */
            model: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** Policy */
        Policy: {
            /**
             * Mode
             * @default filter
             * @enum {string}
             */
            mode: "filter" | "rerank" | "filter_and_rerank" | "fusion";
            /** Min Relevance */
            min_relevance?: number | null;
            /** Top N */
            top_n?: number | null;
            /** Max Context Tokens */
            max_context_tokens?: number | null;
            /**
             * Shadow
             * @default false
             */
            shadow: boolean;
            /** Relevance Guidance */
            relevance_guidance?: string | null;
        };
        /** RankingArm */
        RankingArm: {
            /**
             * Name
             * @enum {string}
             */
            name: "original" | "jev" | "fusion";
            selection: components["schemas"]["SelectionResult"];
            /** Evidence Recall */
            evidence_recall: number | null;
            /** Ndcg */
            ndcg: number | null;
            /** Policy Elapsed Ms */
            policy_elapsed_ms: number;
            /** Stage Elapsed Ms */
            stage_elapsed_ms: number;
            /** Selector Cost Usd */
            selector_cost_usd: number | null;
            /** Total Cost Usd */
            total_cost_usd: number | null;
            answer?: components["schemas"]["Answer"] | null;
            /** Answer Reused From */
            answer_reused_from?: ("original" | "jev" | "fusion") | null;
        };
        /** RankingReport */
        RankingReport: {
            /** Input Hash */
            input_hash: string;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "fixture";
            /** Top N */
            top_n: number;
            /** Arms */
            arms: components["schemas"]["RankingArm"][];
            /**
             * Scoring Calls
             * @default 0
             */
            scoring_calls: number;
            /**
             * Generation Calls
             * @default 0
             */
            generation_calls: number;
            /**
             * Quality Basis
             * @default Binary relevance labels supplied by the caller; candidate evidence recall and nDCG at the shared top-N cutoff (short outputs padded with zero gain). Answer correctness and factual support require review.
             */
            quality_basis: string;
            /**
             * Cost Basis
             * @default Configured API rates: Jev plus generation per deployed arm. Unknown rates/usage stay null. Retrieval, local compute, cache discounts excluded. Shared Jev scoring paid once in this comparison, not once per arm.
             */
            cost_basis: string;
            /**
             * Timing Basis
             * @default Recorded Jev time plus measured policy and generation time; retrieval excluded. This replay is not a fresh latency benchmark. Identical contexts reuse one answer.
             */
            timing_basis: string;
            /**
             * Selection Basis
             * @default Original input order versus Jev ordering versus equal-weight RRF (k=60), same candidate set and top-N/token limits. Pins/groups preserved in all arms. Recorded baseline_ids are not used; original means input-order selection here.
             */
            selection_basis: string;
        };
        /** RankingRequest */
        RankingRequest: {
            record: components["schemas"]["ScoredRun"];
            /**
             * Top N
             * @default 10
             */
            top_n: number;
            /** Max Context Tokens */
            max_context_tokens?: number | null;
        };
        /** ReplayBundle */
        ReplayBundle: {
            record: components["schemas"]["ScoredRun"];
            policy: components["schemas"]["Policy"];
            comparison?: components["schemas"]["Comparison"] | null;
        };
        /** ReplayRequest */
        ReplayRequest: {
            record: components["schemas"]["ScoredRun"];
            policy: components["schemas"]["Policy"];
        };
        /** RunView */
        RunView: {
            record: components["schemas"]["ScoredRun"];
            policy: components["schemas"]["Policy"];
            selection: components["schemas"]["SelectionResult"];
            /** Baseline Ids */
            baseline_ids: string[];
            /** Baseline Context Tokens */
            baseline_context_tokens: number;
            /** Selected Context Tokens */
            selected_context_tokens: number;
            /**
             * Token Estimator
             * @default cl100k_base estimate; actual prompt usage appears after generation
             */
            token_estimator: string;
            /** Evidence Recall */
            evidence_recall: number | null;
            /** Relevant Dropped */
            relevant_dropped: string[] | null;
            /** Baseline Evidence Recall */
            baseline_evidence_recall: number | null;
        };
        /** ScoredRun */
        ScoredRun: {
            request: components["schemas"]["SelectRequest"];
            /** Relevant Ids */
            relevant_ids?: string[] | null;
            /** Baseline Ids */
            baseline_ids?: string[] | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "fixture";
            /**
             * Prompt Version
             * @default useful-evidence-v1
             */
            prompt_version: string;
            /** Input Hash */
            input_hash: string;
            /** Judgments */
            judgments: components["schemas"]["Judgment"][];
            /** Scoring Elapsed Ms */
            scoring_elapsed_ms: number;
            scoring_usage?: components["schemas"]["Usage"] | null;
        };
        /** SelectRequest */
        SelectRequest: {
            /**
             * Mode
             * @default filter
             * @enum {string}
             */
            mode: "filter" | "rerank" | "filter_and_rerank" | "fusion";
            /** Min Relevance */
            min_relevance?: number | null;
            /** Top N */
            top_n?: number | null;
            /** Max Context Tokens */
            max_context_tokens?: number | null;
            /**
             * Shadow
             * @default false
             */
            shadow: boolean;
            /** Relevance Guidance */
            relevance_guidance?: string | null;
            /**
             * Scoring Strategy
             * @default independent
             * @enum {string}
             */
            scoring_strategy: "independent" | "contextual";
            /** Query */
            query: string;
            /** Retrieval Query */
            retrieval_query?: string | null;
            /** Documents */
            documents: components["schemas"]["Document"][];
        };
        /** SelectionResult */
        SelectionResult: {
            /** Documents */
            documents: components["schemas"]["Document"][];
            /** Selected Ids */
            selected_ids: string[] | null;
            /** Decisions */
            decisions: components["schemas"]["Decision"][];
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "shadow" | "bypassed";
            /** Error Code */
            error_code?: string | null;
            /** Models */
            models: string[];
            /**
             * Prompt Version
             * @default useful-evidence-v1
             */
            prompt_version: string;
            /** Policy Version */
            policy_version: string;
            usage: components["schemas"]["Usage"];
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Input Characters */
            input_characters: number;
            /** Selected Characters */
            selected_characters: number | null;
            /** Returned Characters */
            returned_characters: number;
            /**
             * Outcome
             * @default not_evaluated
             * @enum {string}
             */
            outcome: "context_selected" | "no_context_selected" | "not_evaluated";
            /**
             * Top N Exceeded
             * @default false
             */
            top_n_exceeded: boolean;
            /** Selected Context Tokens */
            selected_context_tokens?: number | null;
            /** Context Token Budget Exceeded */
            context_token_budget_exceeded?: boolean | null;
            /**
             * Token Estimator
             * @default cl100k_base passage-text estimate; excludes prompts, separators and output
             */
            token_estimator: string;
        };
        /** StudyRequest */
        StudyRequest: {
            request: components["schemas"]["SelectRequest"];
            /** Relevant Ids */
            relevant_ids?: string[] | null;
            /** Baseline Ids */
            baseline_ids?: string[] | null;
        };
        /** Usage */
        Usage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Completed Documents
             * @default 0
             */
            completed_documents: number;
            /**
             * Complete
             * @default true
             */
            complete: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    config_v1_config_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordings_v1_recordings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    examples_v1_examples_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixture_v1_fixtures__case_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_v1_replay_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_run_v1_import_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayBundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_v1_compare_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_v1_select_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rankings_v1_rankings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ranking_answers_v1_compare_rankings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
